In [14]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
df = pd.read_csv("data/cleaned_diabetic_data.csv")
df.shape

(63595, 40)

In [16]:
df.head()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,...,miglitol,troglitazone,tolazamide,insulin,glyburide-metformin,glipizide-metformin,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,[40-50),1,4,7,14,69,0,16,...,No,No,No,Down,No,No,No,Ch,Yes,0
1,Other,Female,[40-50),1,1,7,14,73,6,26,...,No,No,No,Up,No,No,No,Ch,Yes,0
2,Hispanic,Female,[50-60),1,6,7,14,69,0,25,...,No,No,No,Steady,No,No,No,No,Yes,0
3,AfricanAmerican,Male,[40-50),1,6,7,14,65,2,34,...,No,No,No,Up,No,No,No,Ch,Yes,0
4,Caucasian,Male,[50-60),3,1,1,14,63,4,30,...,No,No,No,Down,No,No,No,Ch,Yes,0

In [17]:
df.isnull().sum()

race                        0
gender                      0
age                         0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df["readmitted"].value_counts()

readmitted
0    59058
1     4537
Name: count, dtype: int64

### Feature Engineering

In [21]:
df.head()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,...,miglitol,troglitazone,tolazamide,insulin,glyburide-metformin,glipizide-metformin,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,[40-50),1,4,7,14,69,0,16,...,No,No,No,Down,No,No,No,Ch,Yes,0
1,Other,Female,[40-50),1,1,7,14,73,6,26,...,No,No,No,Up,No,No,No,Ch,Yes,0
2,Hispanic,Female,[50-60),1,6,7,14,69,0,25,...,No,No,No,Steady,No,No,No,No,Yes,0
3,AfricanAmerican,Male,[40-50),1,6,7,14,65,2,34,...,No,No,No,Up,No,No,No,Ch,Yes,0
4,Caucasian,Male,[50-60),3,1,1,14,63,4,30,...,No,No,No,Down,No,No,No,Ch,Yes,0

NameError: name 'diag_1' is not defined